### PR TITLE
Add a workflow for izhgh

### PR DESCRIPTION
**Pull request by iZhGH**
Created a fork of the lab, added a new branch which is a workflow, workflow is  mean to automate certain aspects of code upon a push or other action. Created a separate branch where we make a yaml file to put all our jobs and steps and names for the workflow. Then we committed our workflow and created this pull request.

### CODE REVIEW

**Comment by thedarkcolour** [comment]
You have a syntax error in Line 3 of your file (one space indent, should be two spaces)
image

**Comment by iZhGH** [comment]
Fixed (hopefully).

**Comment by iZhGH** [comment]
idk whats going on each run has at least one failure

**Comment by thedarkcolour** [comment]
Remove the two spaces behind `jobs:`

**Comment by iZhGH** [comment]
Got it, removed the spaces the 2nd commit but didn't see it failed a separate test, fixed that as well.

**Comment by thedarkcolour** [comment]
Good job

**Pull request merged**
